# Generated by Django 6.0.2 on 2026-02-25 14:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('property_type', models.CharField(max_length=50)),
                ('bedrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3)),
                ('max_guests', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('square_feet', models.IntegerField(blank=True, null=True)),
                ('amenities', models.JSONField(default=dict)),
                ('family_features', models.JSONField(default=dict)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('featured_image', models.ImageField(upload_to='properties/featured/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0)),
                ('host', models.ForeignKey(limit_choices_to={'role': 'HOST'}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/')),
                ('is_featured', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['-is_featured', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['host', 'status'], name='properties__host_id_c5f9b4_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'country'], name='properties__city_45e90f_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_available'], name='properties__is_avai_04f37a_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['property', 'date', 'is_available'], name='properties__propert_7504d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('property', 'date')},
        ),
    ]
